### ISSUE TITLE
Advice to run vosk without hassio-addons

### ISSUE THREAD

**Issue by sebPomme** [rhasspy/hassio-addons#52]
Hi, I didn't have hassio-addons and I want to run vosk.

I try this:  
my `docker-compose.yml` file
```yaml
services:
  engine:
    restart: always
    image: rhasspy/wyoming-vosk:1.3.1
    build:
      context: https://github.com/rhasspy/hassio-addons.git#:vosk
      args:
        BUILD_FROM: ghcr.io/home-assistant/aarch64-base-debian:bookworm
        WYOMING_VOSK_VERSION: 1.3.1
    ports:
      - 10300:10300
    volumes:
      - /srv/docker_data/vosk:/data
```
I put this configuration file in `/srv/docker_data/vosk/options.json` 
```json
{ 
  "debug_logging": "true",
  "correct_sentences": "0.0",
  "preload_language": "fr"
}
```
It's build. Then fail with on the run with 
```
pomme@box# docker compose up
[+] Running 1/1
 ✔ Container wyoming-vosk-engine-1  Recreated                                                                                                                                             1.1s 
Attaching to wyoming-vosk-engine-1
wyoming-vosk-engine-1  | s6-rc: info: service s6rc-oneshot-runner: starting
wyoming-vosk-engine-1  | s6-rc: info: service s6rc-oneshot-runner successfully started
wyoming-vosk-engine-1  | s6-rc: info: service fix-attrs: starting
wyoming-vosk-engine-1  | s6-rc: info: service fix-attrs successfully started
wyoming-vosk-engine-1  | s6-rc: info: service legacy-cont-init: starting
wyoming-vosk-engine-1  | s6-rc: info: service legacy-cont-init successfully started
wyoming-vosk-engine-1  | s6-rc: info: service vosk: starting
wyoming-vosk-engine-1  | s6-rc: info: service vosk successfully started
wyoming-vosk-engine-1  | s6-rc: info: service discovery: starting
wyoming-vosk-engine-1  | curl: (6) Could not resolve host: supervisor
wyoming-vosk-engine-1  | [23:58:54] ERROR: Something went wrong contacting the API
wyoming-vosk-engine-1  | usage: __main__.py [-h] [--uri URI] --data-dir DATA_DIR
wyoming-vosk-engine-1  |                    [--download-dir DOWNLOAD_DIR] [--language LANGUAGE]
wyoming-vosk-engine-1  |                    [--preload-language PRELOAD_LANGUAGE]
wyoming-vosk-engine-1  |                    [--model-for-language language model]
wyoming-vosk-engine-1  |                    [--casing-for-language language casing]
wyoming-vosk-engine-1  |                    [--model-index MODEL_INDEX] [--sentences-dir SENTENCES_DIR]
wyoming-vosk-engine-1  |                    [--database-dir DATABASE_DIR]
wyoming-vosk-engine-1  |                    [--correct-sentences [CORRECT_SENTENCES]]
wyoming-vosk-engine-1  |                    [--limit-sentences] [--allow-unknown] [--debug]
wyoming-vosk-engine-1  | __main__.py: error: argument --correct-sentences: invalid float value: 'null'
wyoming-vosk-engine-1  | [23:58:56] INFO: Service exited with code 2 (by signal 0)
```
It's looks like [this line](https://github.com/rhasspy/hassio-addons/blob/master/vosk/rootfs/etc/s6-overlay/s6-rc.d/vosk/run#L35) fail but I can't find why.

Maybe I miss something obvious for a pro adddons user ? Mayby I have to put options.json somewhere else ? 

Any help will be appreciated

pomme :apple:
